name: cryptoapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  firebase_storage: ^10.2.18
  pin_code_fields: ^7.4.0
  google_sign_in: ^5.3.3
  provider: ^6.0.3
  http: ^0.13.4
  syncfusion_flutter_charts: ^20.2.36
  flutter_svg: ^1.1.1+1
  google_nav_bar: ^5.0.6
  flutter_secure_storage: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/icons/
    - assets/

  fonts:
    - family: Montreal
      fonts:
        - asset: assets/fonts/Montreal-Regular.ttf

    - family: Myriadpro
      fonts:
        - asset: assets/fonts/MYRIADPRO-REGULAR.OTF
