// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ6HP3AjkJbh4BJtUNj1fZ-Yo-RKXwkpo',
    appId: '1:504753340563:android:54c34d88f253e31cf78d66',
    messagingSenderId: '504753340563',
    projectId: 'cryptoapp-88674',
    storageBucket: 'cryptoapp-88674.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoz5AEiCvRroIZbuU2b-_kooitIjT28H8',
    appId: '1:504753340563:ios:8fa2838013073184f78d66',
    messagingSenderId: '504753340563',
    projectId: 'cryptoapp-88674',
    storageBucket: 'cryptoapp-88674.appspot.com',
    androidClientId: '504753340563-2q0q2kqhdn5v05ib8bqj2i3fi8gh1673.apps.googleusercontent.com',
    iosClientId: '504753340563-hjk36hld9irgfluoqf3h9cvsuar5d9ns.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoapp',
  );
}
